FROM apache/spark:3.5.0

USER root

# Install Python dependencies needed by bronze_consumer.py and Delta Merge
RUN pip install --no-cache-dir \
    python-dotenv==1.0.1 \
    delta-spark==3.2.0

# Download required JARs into Spark's jars directory
# -- Azure ADLS Gen2 Connectivity --
RUN cd /opt/spark/jars && \
    curl -LO https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-azure/3.3.4/hadoop-azure-3.3.4.jar && \
    curl -LO https://repo1.maven.org/maven2/org/wildfly/openssl/wildfly-openssl/1.1.3.Final/wildfly-openssl-1.1.3.Final.jar && \
    curl -LO https://repo1.maven.org/maven2/com/azure/azure-storage-blob/12.25.1/azure-storage-blob-12.25.1.jar && \
    curl -LO https://repo1.maven.org/maven2/com/azure/azure-storage-common/12.24.1/azure-storage-common-12.24.1.jar && \
    curl -LO https://repo1.maven.org/maven2/com/azure/azure-core/1.45.1/azure-core-1.45.1.jar && \
    curl -LO https://repo1.maven.org/maven2/com/azure/azure-core-http-netty/1.14.0/azure-core-http-netty-1.14.0.jar && \
    curl -LO https://repo1.maven.org/maven2/com/azure/azure-identity/1.11.1/azure-identity-1.11.1.jar && \
    curl -LO https://repo1.maven.org/maven2/com/microsoft/azure/msal4j/1.14.0/msal4j-1.14.0.jar

# -- Kafka Connector --
RUN cd /opt/spark/jars && \
    curl -LO https://repo1.maven.org/maven2/org/apache/spark/spark-sql-kafka-0-10_2.12/3.5.0/spark-sql-kafka-0-10_2.12-3.5.0.jar && \
    curl -LO https://repo1.maven.org/maven2/org/apache/kafka/kafka-clients/3.5.1/kafka-clients-3.5.1.jar && \
    curl -LO https://repo1.maven.org/maven2/org/apache/spark/spark-token-provider-kafka-0-10_2.12/3.5.0/spark-token-provider-kafka-0-10_2.12-3.5.0.jar && \
    curl -LO https://repo1.maven.org/maven2/org/apache/commons/commons-pool2/2.11.1/commons-pool2-2.11.1.jar

# -- Delta Lake --
RUN cd /opt/spark/jars && \
    curl -LO https://repo1.maven.org/maven2/io/delta/delta-spark_2.12/3.2.0/delta-spark_2.12-3.2.0.jar && \
    curl -LO https://repo1.maven.org/maven2/io/delta/delta-storage/3.2.0/delta-storage-3.2.0.jar

USER spark
