FROM apache/airflow:2.7.3

USER root
# Install Java (Required for PySpark)
RUN apt-get update && \
    apt-get install -y openjdk-17-jre-headless && \
    apt-get clean

USER airflow
# Install PySpark and Delta-Spark
RUN pip install --no-cache-dir pyspark==3.5.0 delta-spark==3.2.0
